# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('img', models.ImageField(blank=True, upload_to='img', verbose_name='\u7f29\u7565\u56fe')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Product', verbose_name='\u6240\u5c5e\u4ea7\u54c1')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u4ea7\u54c1\u5b9e\u4f8b',
                'verbose_name_plural': '\u4ea7\u54c1\u5b9e\u4f8b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u6d4b\u8bd5\u9879',
                'verbose_name_plural': '\u6d4b\u8bd5\u9879\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ValidationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u9a8c\u8bc1\u9636\u6bb5',
                'verbose_name_plural': '\u9a8c\u8bc1\u9636\u6bb5\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='product',
            name='validation_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.ValidationPhase', verbose_name='\u9a8c\u8bc1\u9636\u6bb5'),
        ),
    ]
