# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='product_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.ProductInstance', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u5b9e\u4f8b'),
            preserve_default=False,
        ),
    ]
