# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0002_testitem_product_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='code',
            field=models.TextField(default=1, help_text='\u6d4b\u8bd5\u9879\u5b8c\u6574python\u4ee3\u7801', verbose_name='\u6d4b\u8bd5\u9879\u4ee3\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testitem',
            name='parameters',
            field=models.TextField(default=1, help_text='\u6d4b\u8bd5\u9879\u7684\u53c2\u6570\u53ea\u8981\u4e0e\u4ee3\u7801\u5bf9\u5e94\uff0c\u4efb\u4f55\u683c\u5f0f\u90fd\u53ef\u4ee5\u3002', verbose_name='\u6d4b\u8bd5\u9879\u53c2\u6570'),
            preserve_default=False,
        ),
    ]
