# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0004_task_taskstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='test_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.TestItem', verbose_name='\u6240\u5c5e\u6d4b\u8bd5\u9879'),
            preserve_default=False,
        ),
    ]
