# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0006_auto_20170407_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('creator', models.CharField(max_length=255, verbose_name='\u521b\u5efa\u8005')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('uuid', models.UUIDField(unique=True, verbose_name='\u5b9e\u4f8bID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Task')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u6d4b\u8bd5\u4efb\u52a1\u5b9e\u4f8b',
                'verbose_name_plural': '\u6d4b\u8bd5\u4efb\u52a1\u5b9e\u4f8b\u5217\u8868',
            },
        ),
    ]
