# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0007_taskinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'ordering': ('task_instance', 'created'),
                'verbose_name': '\u6d4b\u8bd5\u4efb\u52a1\u7ed3\u679c',
                'verbose_name_plural': '\u6d4b\u8bd5\u4efb\u52a1\u7ed3\u679c\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Task', verbose_name='\u6240\u5c5e\u6d4b\u8bd5\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='results', to='ate_tasks.TaskInstance', verbose_name='\u6240\u5c5e\u6d4b\u8bd5\u4efb\u52a1'),
        ),
    ]
