# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0008_auto_20170407_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='result',
            field=models.TextField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c'),
        ),
    ]
