# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:07
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0009_auto_20170407_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='\u5b9e\u4f8bID'),
        ),
    ]
