# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0010_auto_20170407_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinstance',
            options={'ordering': ('created',), 'verbose_name': '\u6d4b\u8bd5\u4efb\u52a1\u5b9e\u4f8b', 'verbose_name_plural': '\u6d4b\u8bd5\u4efb\u52a1\u5b9e\u4f8b\u5217\u8868'},
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='name',
        ),
    ]
