# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0011_auto_20170407_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='name',
            field=models.CharField(default='test', max_length=255, unique=True, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
