# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 11:44
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0013_auto_20170408_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='result_id',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='测试结果ID'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='result',
            field=models.TextField(blank=True, verbose_name='测试结果'),
        ),
    ]
