# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0018_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('message_type',), 'verbose_name': 'ICD消息', 'verbose_name_plural': 'ICD消息列表'},
        ),
    ]
