# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0019_auto_20170418_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('ate_validation_phase', '验证阶段管理'), ('ate_project', '项目管理'), ('ate_product', '产品管理'), ('ate_product_instance', '产品实例管理'), ('ate_test_item', '测试项管理'), ('ate_tasks', '测试任务管理')),
            },
        ),
    ]
