# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 06:14
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0022_message_icd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
    ]
