# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 06:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0023_auto_20170423_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='icd_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ate_tasks.IcdInfo', verbose_name='所属ICD类别'),
        ),
    ]
