# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0024_auto_20170423_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='message', max_length=255, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
