# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 06:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0025_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='product_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.ProductInstance', verbose_name='所属产品实例'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Product', verbose_name='所属产品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ate_tasks.Project', verbose_name='所属项目'),
            preserve_default=False,
        ),
    ]
