# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0027_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='product_instance',
        ),
    ]
