# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0028_remove_testitem_product_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='expected',
            field=models.TextField(blank=True, verbose_name='合格判据'),
        ),
    ]
