# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 07:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0029_testitem_expected'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcdBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=255, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='IcdDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('domain_type', models.CharField(max_length=255, verbose_name='type')),
                ('start_bits', models.IntegerField(verbose_name='start_bits')),
                ('end_bits', models.IntegerField(verbose_name='end_bits')),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcdMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('message_id', models.CharField(max_length=255, verbose_name='id')),
                ('message_attributes', models.TextField(verbose_name='attributes')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ate_tasks.IcdBus')),
            ],
        ),
        migrations.CreateModel(
            name='IcdProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('project_id', models.CharField(max_length=255, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='IcdProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('project_id', models.CharField(max_length=255, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='IcdSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('length', models.IntegerField(verbose_name='length')),
                ('start', models.IntegerField(verbose_name='start')),
                ('end', models.IntegerField(verbose_name='end')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='ate_tasks.IcdMessage')),
            ],
        ),
        migrations.AddField(
            model_name='icdproduct',
            name='icd_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ate_tasks.IcdProject'),
        ),
        migrations.AddField(
            model_name='icddomain',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ate_tasks.IcdSignal'),
        ),
        migrations.AddField(
            model_name='icdbus',
            name='icd_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='ate_tasks.IcdProduct'),
        ),
    ]
