# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0031_auto_20170604_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdmessage',
            name='message_attributes',
            field=models.TextField(blank=True, verbose_name='attributes'),
        ),
    ]
