# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0032_auto_20170604_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icdbus',
            name='icd_product',
        ),
        migrations.AddField(
            model_name='icdmessage',
            name='icd_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ate_tasks.IcdProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icdmessage',
            name='bus',
            field=models.CharField(max_length=255, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='IcdBus',
        ),
    ]
