# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0033_auto_20170621_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdmessage',
            name='bus',
            field=models.CharField(max_length=255, verbose_name='bus_type'),
        ),
    ]
