# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0035_icdinfo_icd_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='icd_type',
        ),
        migrations.RenameField(
            model_name='icdproduct',
            old_name='project_id',
            new_name='product_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
