# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0038_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='channels',
            field=models.TextField(blank=True, verbose_name='通道信息'),
        ),
        migrations.AddField(
            model_name='device',
            name='parameters',
            field=models.TextField(blank=True, verbose_name='配置参数'),
        ),
        migrations.AlterField(
            model_name='device',
            name='bus',
            field=models.CharField(max_length=255, verbose_name='总线类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ate_tasks.ServiceNode', verbose_name='所属节点'),
        ),
    ]
