# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0039_auto_20170621_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='运行中'),
        ),
    ]
