# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:31
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0040_device_is_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='监控ID号')),
                ('rules', models.TextField(blank=True, verbose_name='订阅规则')),
            ],
        ),
    ]
