# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0041_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='名称'),
        ),
    ]
