# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0042_monitor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='name',
        ),
    ]
