# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0043_remove_monitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='是否正在运行'),
        ),
    ]
