# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0045_auto_20170705_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icdinfo',
            name='icd_project',
        ),
        migrations.DeleteModel(
            name='IcdInfo',
        ),
    ]
