# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0049_auto_20170707_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='child',
        ),
        migrations.RemoveField(
            model_name='building',
            name='block',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='building',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
