# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0051_device_device_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='StimulateFormFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=255, unique=True, verbose_name='总线类型')),
                ('content', models.TextField(verbose_name='表单结构')),
            ],
            options={
                'verbose_name': '静态激励表单结构',
                'verbose_name_plural': '静态激励表单结构列表',
                'ordering': ('bus_type',),
            },
        ),
    ]
