# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0052_stimulateformformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulateformformat',
            name='content',
            field=models.TextField(blank=True, verbose_name='表单结构'),
        ),
    ]
