# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0053_auto_20170710_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stimulateformformat',
            options={'ordering': ('bus_type',), 'verbose_name': '静态激励消息表单结构', 'verbose_name_plural': '静态激励消息表单结构列表'},
        ),
    ]
