# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0055_stimulateformstructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StimulateFormFormat',
        ),
    ]
