# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0058_auto_20170710_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceformstructure',
            old_name='content',
            new_name='device_content',
        ),
    ]
