# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0059_auto_20170710_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceformstructure',
            name='channels_content',
            field=models.TextField(blank=True, verbose_name='通道绑定结构'),
        ),
    ]
