# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0060_deviceformstructure_channels_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icdmessage',
            old_name='message_attributes',
            new_name='attributes',
        ),
    ]
