# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0061_auto_20170713_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icddomain',
            name='domain_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icddomain',
            name='end_bits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icddomain',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icddomain',
            name='start_bits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icdmessage',
            name='attributes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icdmessage',
            name='bus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdmessage',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='icdmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdproduct',
            name='product_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='icdproduct',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdproject',
            name='project_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='icdproject',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdsignal',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icdsignal',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icdsignal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icdsignal',
            name='start',
            field=models.IntegerField(),
        ),
    ]
