# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0062_auto_20170713_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icdmessage',
            name='attributes',
        ),
    ]
