# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0065_auto_20170713_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdproduct',
            name='attrs',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='icdproject',
            name='attrs',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
