# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0066_auto_20170713_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bindings',
            field=models.TextField(blank=True, verbose_name='消息绑定'),
        ),
    ]
