# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0067_device_bindings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='channels',
            field=models.TextField(blank=True, default=[], verbose_name='通道信息'),
        ),
        migrations.AlterField(
            model_name='device',
            name='parameters',
            field=models.TextField(blank=True, default=[], verbose_name='配置参数'),
        ),
    ]
