# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0068_auto_20170713_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBindingFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=255, verbose_name='总线类型')),
                ('content', models.TextField(help_text='http://www.alpacajs.org', verbose_name='表单样式')),
            ],
        ),
    ]
