# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0069_devicebindingformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_binding_schema', models.TextField(blank=True)),
                ('device_binding_option', models.TextField(blank=True)),
            ],
        ),
    ]
