# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0072_auto_20170714_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceBindingFormat',
        ),
    ]
