# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 23:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0073_delete_devicebindingformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StimulateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('creator', models.CharField(max_length=255, verbose_name='创建者')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('description', models.TextField(blank=True, verbose_name='描述信息')),
                ('content', models.TextField(blank=True, default='[]')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ate_tasks.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ate_tasks.Project')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '激励序列',
                'verbose_name_plural': '激励序列列表',
            },
        ),
        migrations.DeleteModel(
            name='DeviceFormStructure',
        ),
        migrations.DeleteModel(
            name='StimulateFormStructure',
        ),
    ]
