# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0074_auto_20170717_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('content', models.TextField()),
            ],
        ),
    ]
