# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0075_monitorrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bustype',
            options={'ordering': ('name',), 'verbose_name': '总线类型', 'verbose_name_plural': '总线类型列表'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name': '测试资源', 'verbose_name_plural': '测试资源列表'},
        ),
        migrations.AlterModelOptions(
            name='servicenode',
            options={'ordering': ('ip',), 'verbose_name': '服务节点', 'verbose_name_plural': '服务节点列表'},
        ),
    ]
