# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_tasks', '0076_auto_20170717_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustype',
            name='message_schema',
            field=models.TextField(blank=True, default='{}', help_text='消息内容编辑时需要用到'),
        ),
    ]
