# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('price', models.CharField(max_length=50, verbose_name='产品价格')),
            ],
        ),
    ]
